"""
Helper utilities used across the project
"""
import json
from pathlib import Path
from datetime import datetime


def save_json(data, filepath):
    """
    Save data to a JSON file
    
    Args:
        data: Python dict or list to save
        filepath: Path to save the file
    """
    filepath = Path(filepath)
    filepath.parent.mkdir(parents=True, exist_ok=True)
    
    with open(filepath, 'w') as f:
        json.dump(data, f, indent=2)
    
    print(f"✓ Saved to {filepath}")


def load_json(filepath):
    """
    Load data from a JSON file
    
    Args:
        filepath: Path to the JSON file
    
    Returns:
        Loaded data
    """
    with open(filepath, 'r') as f:
        return json.load(f)


def clean_sql(sql):
    """
    Clean up SQL generated by LLM
    
    Args:
        sql: Raw SQL string from LLM
    
    Returns:
        Cleaned SQL string
    """
    # Remove markdown code blocks
    sql = sql.replace("```sql", "").replace("```", "")
    
    # Remove extra whitespace
    sql = sql.strip()
    
    return sql


def format_timestamp():
    """
    Get current timestamp as string
    
    Returns:
        Formatted timestamp string
    """
    return datetime.now().strftime("%Y-%m-%d %H:%M:%S")


def truncate_text(text, max_length=500):
    """
    Truncate text to a maximum length
    
    Args:
        text: Text to truncate
        max_length: Maximum length
    
    Returns:
        Truncated text
    """
    if len(text) <= max_length:
        return text
    
    return text[:max_length] + "..."


# Test the helpers
if __name__ == "__main__":
    print("Testing helpers...")
    
    # Test save/load JSON
    test_data = {"name": "test", "value": 123}
    save_json(test_data, "test_output.json")
    loaded = load_json("test_output.json")
    print(f"Loaded: {loaded}")
    
    # Test SQL cleaning
    dirty_sql = "```sql\nSELECT * FROM users;\n```"
    clean = clean_sql(dirty_sql)
    print(f"Cleaned SQL: {clean}")
    
    # Test timestamp
    print(f"Timestamp: {format_timestamp()}")
    
    print("✓ All helpers working!")